### ISSUE TITLE
Sign in problem with numbers

### ISSUE THREAD

**Issue by diack** [pikpok/fitness-club#8] opened 2015-05-22 15:36 UTC
**Area**: User Interface
**Severity**: high
**Priority**: high
**Environment**: Development
**Build number**: latest in production
**Steps to reproduce**:
1.Click sign in button
2.Put login with number
**Actual result**:Application reject registration
**Expected result**: Registration should be completed

**Comment by pikpok** [comment] 2015-05-23 12:57
can't reproduce, closing

**Closed by pikpok** 2015-05-23 12:57 UTC
Labels: invalid
