### ISSUE TITLE
User name can not be updated

### ISSUE THREAD

**Issue by diack** [pikpok/fitness-club#6] opened 2015-05-22 15:27 UTC
**Area**: User Interface
**Severity**: medium
**Priority**: medium
**Environment**: Development
**Build number**:1
**Steps to reproduce**:
1. Open user control panel
2.Click update the name
3.Write a name
4.Save update
**Actual result**: Name dosent change
**Expected result**: Name should be changed

**Comment by pikpok** [comment] 2015-05-22 20:36
duplicate of #1, and it's fixed now, closing :)

**Closed by pikpok** 2015-05-22 20:36 UTC
Labels: duplicate
