### ISSUE TITLE
Multiple click on icon cause delay

### ISSUE THREAD

**Issue by diack** [pikpok/fitness-club#9] opened 2015-05-22 15:41 UTC
**Area**:User Interface
**Severity**: medium
**Priority**:medium
**Environment**:Development
**Build number**: latest in production
**Steps to reproduce**:
1.Multiple fast click on icon
**Actual result**:Icon doesn't response or response after 20s.
**Expected result**:Icon should redirect me to proper website

**Comment by pikpok** [comment] 2015-05-23 12:56
I can't reproduce it, closing

**Closed by pikpok** 2015-05-23 12:56 UTC
