### ISSUE TITLE
User last name cant be update

### ISSUE THREAD

**Issue by diack** [pikpok/fitness-club#14] opened 2015-05-22 16:02 UTC
**Area**: User Interface
**Severity**: medium
**Priority**: medium
**Environment**: Development
**Build number**:latest in production
1.Log in
2.Go user panel
3.Change last name
4.Click update
**Actual result**: Last name cant be updated
**Expected result**: Last name should be updated

**Comment by pikpok** [comment] 2015-05-22 20:32
duplicate of #1 and is fixed now :)

**Closed** 2015-05-22 20:32 UTC
Labels: duplicate
